# Prism 数学 API
from Prism.Math.Vector2 import Vector2
from Prism.Math.Vector3 import Vector3
from Prism.Math.Vector4 import Vector4
from Prism.Math.Quaternion import Quaternion
from Prism.Math.Mathf import Mathf
from Prism.Math.Noise import Noise
from Prism.Math.Interpolate import Interpolate
from Prism.Math.Matrix4 import Matrix4
