# PrismNative 原生模块类型存根（由 C++ PYBIND11_MODULE 在运行时动态创建）

from typing import Optional

# ════════════════════════════════════════════
#  Log
# ════════════════════════════════════════════

def Prism_Log_LogMessage(level: int, message: str) -> None: ...
    """level: Trace=1, Debug=2, Info=4, Warn=8, Error=16, Critical=32"""

# ════════════════════════════════════════════
#  Time
# ════════════════════════════════════════════

def Prism_Time_GetDeltaTime() -> float: ...
def Prism_Time_GetUnscaledDeltaTime() -> float: ...
def Prism_Time_GetTime() -> float: ...
def Prism_Time_GetUnscaledTime() -> float: ...
def Prism_Time_GetFixedDeltaTime() -> float: ...
def Prism_Time_GetFrameCount() -> int: ...
def Prism_Time_SetTimeScale(scale: float) -> None: ...
def Prism_Time_GetTimeScale() -> float: ...
def Prism_Time_SetFixedDeltaTime(fixedDeltaTime: float) -> None: ...

# ════════════════════════════════════════════
#  Math
# ════════════════════════════════════════════

def Prism_Noise_PerlinNoise(x: float, y: float) -> float: ...

# ════════════════════════════════════════════
#  Input
# ════════════════════════════════════════════

def Prism_Input_IsKeyPressed(key: int) -> bool: ...
def Prism_Input_GetMousePosition() -> tuple[float, float]: ...
def Prism_Input_SetCursorMode(mode: int) -> None: ...
def Prism_Input_GetCursorMode() -> int: ...
def Prism_Input_IsMouseButtonPressed(button: int) -> bool: ...

# ════════════════════════════════════════════
#  Entity
# ════════════════════════════════════════════

def Prism_Entity_CreateComponent(entityID: int, cls: type) -> None: ...
def Prism_Entity_HasComponent(entityID: int, cls: type) -> bool: ...
def Prism_Entity_AddBehaviour(entityID: int, cls: type) -> object: ...
def Prism_Entity_FindEntityByTag(tag: str) -> int: ...
def Prism_Entity_RemoveBehaviour(entityID: int, behaviourID: int) -> None: ...
def Prism_Entity_GetBehaviour(entityID: int, cls: type) -> object: ...
def Prism_Behaviour_GetEnabled(behaviourID: int) -> bool: ...
def Prism_Behaviour_SetEnabled(behaviourID: int, enabled: bool) -> None: ...

# ════════════════════════════════════════════
#  TagComponent
# ════════════════════════════════════════════

def Prism_TagComponent_GetTag(entityID: int) -> str: ...
def Prism_TagComponent_SetTag(entityID: int, tag: str) -> None: ...

# ════════════════════════════════════════════
#  TransformComponent
# ════════════════════════════════════════════

def Prism_TransformComponent_GetPosition(entityID: int) -> tuple[float, float, float]: ...
def Prism_TransformComponent_SetPosition(entityID: int, pos: tuple[float, float, float]) -> None: ...
def Prism_TransformComponent_GetRotation(entityID: int) -> tuple[float, float, float]: ...
def Prism_TransformComponent_SetRotation(entityID: int, rotation: tuple[float, float, float]) -> None: ...
def Prism_TransformComponent_GetScale(entityID: int) -> tuple[float, float, float]: ...
def Prism_TransformComponent_SetScale(entityID: int, scale: tuple[float, float, float]) -> None: ...
def Prism_TransformComponent_GetUp(entityID: int) -> tuple[float, float, float]: ...
def Prism_TransformComponent_GetRight(entityID: int) -> tuple[float, float, float]: ...
def Prism_TransformComponent_GetForward(entityID: int) -> tuple[float, float, float]: ...
def Prism_TransformComponent_GetLocalPosition(entityID: int) -> tuple[float, float, float]: ...
def Prism_TransformComponent_SetLocalPosition(entityID: int, pos: tuple[float, float, float]) -> None: ...
def Prism_TransformComponent_GetLocalRotation(entityID: int) -> tuple[float, float, float]: ...
def Prism_TransformComponent_SetLocalRotation(entityID: int, rotation: tuple[float, float, float]) -> None: ...
def Prism_TransformComponent_GetLocalScale(entityID: int) -> tuple[float, float, float]: ...
def Prism_TransformComponent_SetLocalScale(entityID: int, scale: tuple[float, float, float]) -> None: ...
def Prism_TransformComponent_GetTransform(entityID: int) -> object: ...
    """返回 ScriptTransform 对象，有 Position/Rotation/Scale/Up/Right/Forward 字段"""
def Prism_TransformComponent_SetTransform(entityID: int, transform: object) -> None: ...

# ════════════════════════════════════════════
#  MeshRendererComponent
# ════════════════════════════════════════════

def Prism_MeshRendererComponent_GetMesh(entityID: int) -> int: ...
def Prism_MeshRendererComponent_SetMesh(entityID: int, handle: int) -> None: ...
def Prism_MeshRendererComponent_GetMaterial(entityID: int, index: int) -> int: ...
def Prism_MeshRendererComponent_SetMaterial(entityID: int, index: int, handle: int) -> None: ...
def Prism_MeshRendererComponent_GetMaterialCount(entityID: int) -> int: ...
def Prism_MeshRendererComponent_GetMaterials(entityID: int) -> list: ...
def Prism_MeshRendererComponent_SetMaterials(entityID: int, handles: tuple) -> None: ...

# ════════════════════════════════════════════
#  Mesh
# ════════════════════════════════════════════

def Prism_Mesh_Constructor(filepath: str) -> int: ...
    """返回 mesh handle"""
def Prism_Mesh_Destructor(handle: int) -> None: ...

# ════════════════════════════════════════════
#  MeshFactory
# ════════════════════════════════════════════

def Prism_MeshFactory_CreatePlane(width: float, height: float) -> int: ...

# ════════════════════════════════════════════
#  Texture2D
# ════════════════════════════════════════════

def Prism_Texture2D_Constructor(width: int, height: int) -> int: ...
def Prism_Texture2D_Destructor(handle: int) -> None: ...

# ════════════════════════════════════════════
#  RigidBody2DComponent
# ════════════════════════════════════════════

def Prism_RigidBody2DComponent_ApplyLinearImpulse(entityID: int, impulse: tuple[float, float], offset: tuple[float, float], wake: bool) -> None: ...
def Prism_RigidBody2DComponent_GetLinearVelocity(entityID: int) -> tuple[float, float]: ...
def Prism_RigidBody2DComponent_SetLinearVelocity(entityID: int, velocity: tuple[float, float]) -> None: ...

# ════════════════════════════════════════════
#  RigidBodyComponent (3D)
# ════════════════════════════════════════════

def Prism_RigidBodyComponent_AddForce(entityID: int, force: tuple[float, float, float], forceMode: int) -> None: ...
def Prism_RigidBodyComponent_AddTorque(entityID: int, torque: tuple[float, float, float], forceMode: int) -> None: ...
def Prism_RigidBodyComponent_GetLinearVelocity(entityID: int) -> tuple[float, float, float]: ...
def Prism_RigidBodyComponent_SetLinearVelocity(entityID: int, velocity: tuple[float, float, float]) -> None: ...
def Prism_RigidBodyComponent_Rotate(entityID: int, rotation: tuple[float, float, float]) -> None: ...
def Prism_RigidBodyComponent_GetLayer(entityID: int) -> int: ...
def Prism_RigidBodyComponent_GetMass(entityID: int) -> float: ...
def Prism_RigidBodyComponent_SetMass(entityID: int, mass: float) -> None: ...
def Prism_RigidBodyComponent_GetBodyType(entityID: int) -> int: ...
    """0=Static, 1=Dynamic"""
def Prism_RigidBodyComponent_GetAngularVelocity(entityID: int) -> tuple[float, float, float]: ...
def Prism_RigidBodyComponent_SetAngularVelocity(entityID: int, velocity: tuple[float, float, float]) -> None: ...

# ════════════════════════════════════════════
#  Physics
# ════════════════════════════════════════════

def Prism_Physics_Raycast(origin: tuple[float, float, float], direction: tuple[float, float, float], maxDistance: float) -> Optional[object]: ...
    """返回 RaycastHit 对象（EntityID, Position, Normal, Distance）或 None"""
def Prism_Physics_OverlapBox(origin: tuple[float, float, float], halfSize: tuple[float, float, float]) -> list: ...
def Prism_Physics_OverlapSphere(origin: tuple[float, float, float], radius: float) -> list: ...
def Prism_Physics_OverlapCapsule(origin: tuple[float, float, float], radius: float, halfHeight: float) -> list: ...
def Prism_Physics_GetGravity() -> float: ...
def Prism_Physics_SetGravity(gravity: float) -> None: ...

# ════════════════════════════════════════════
#  Material
# ════════════════════════════════════════════

def Prism_Material_Constructor(shaderName: str) -> int: ...
def Prism_Material_Destructor(handle: int) -> None: ...
def Prism_Material_SetFloat(handle: int, uniform: str, value: float) -> None: ...
def Prism_Material_SetInt(handle: int, uniform: str, value: int) -> None: ...
def Prism_Material_SetBool(handle: int, uniform: str, value: bool) -> None: ...
def Prism_Material_SetVector2(handle: int, uniform: str, value: tuple[float, float]) -> None: ...
def Prism_Material_SetVector3(handle: int, uniform: str, value: tuple[float, float, float]) -> None: ...
def Prism_Material_SetVector4(handle: int, uniform: str, value: tuple[float, float, float, float]) -> None: ...
def Prism_Material_SetColor3(handle: int, uniform: str, value: tuple[float, float, float]) -> None: ...
def Prism_Material_SetColor(handle: int, uniform: str, value: tuple[float, float, float, float]) -> None: ...
def Prism_Material_SetMatrix4(handle: int, uniform: str, value: tuple) -> None: ...
def Prism_Material_SetTexture(handle: int, uniform: str, texHandle: int) -> None: ...
def Prism_Material_SetKeyword(handle: int, name: str, enabled: bool) -> None: ...
def Prism_Material_IsKeywordEnabled(handle: int, name: str) -> bool: ...
