# PrismEngine 原生模块类型

import ctypes
from typing import (Any, Callable, Generator, Generic, Iterable, List, Literal,
                    Optional, SupportsInt, Tuple, Type, TypeVar, Union,
                    overload)

T = TypeVar("T")

# Math
class vec2: ...
class vec3: ...
class vec4: ...

# Assets 
class Asset:
    @overload
    def __init__(self, handle: int) -> None: ...
    def __repr__(self) -> str: ...
class Mesh(Asset):
    @overload
    def __init__(self, handle: int) -> None: ...
    @overload
    def __init__(self, filePath: str) -> None: ...
    def __repr__(self) -> str: ...
class Texture2D(Asset):
    @overload
    def __init__(self, handle: int) -> None: ...
    @overload
    def __init__(self, width: int, height: int) -> None: ...
    def __repr__(self) -> str: ...
class Material(Asset):
    @overload
    def __init__(self, handle: int) -> None: ...
    @overload
    def __init__(self, shaderName: str) -> None: ...
    def __repr__(self) -> str: ...
    def SetFloat(self, uniform: str, value: float) -> None: ...
    def SetInt(self, uniform: str, value: int) -> None: ...
    def SetBool(self, uniform: str, value: bool) -> None: ...
    def SetVector2(self, uniform: str, value: vec2) -> None: ...
    def SetVector3(self, uniform: str, value: vec3) -> None: ...
    def SetVector4(self, uniform: str, value: vec4) -> None: ...
    def SetColor3(self, uniform: str, value: vec3) -> None: ...
    def SetColor(self, uniform: str, value: vec4) -> None: ...
    def SetMatrix4(self, uniform: str, value: Any) -> None: ...
    def SetTexture(self, uniform: str, texture: Texture2D) -> None: ...
    def SetKeyword(self, name: str, enabled: bool) -> None: ...
    def IsKeywordEnabled(self, name: str) -> bool: ...


# ECS

class Entity:
    def __init__(self, id: int = 0) -> None: ...
    @property
    def ID(self) -> int: ...
    @ID.setter
    def ID(self, value: int) -> None: ...
    @property
    def Transform(self) -> TransformComponent: ...
    def GetComponent(self, cls: Type[T]) -> Optional[T]: ...
    def CreateComponent(self, cls: Type[T]) -> Optional[T]: ...
    def HasComponent(self, cls: type) -> bool: ...
    @staticmethod
    def FindEntityByTag(tag: str) -> Optional[Entity]: ...
    @staticmethod
    def FindEntityByID(id: int) -> "Entity": ...

class Component:
    def __init__(self) -> None: ...
    @property
    def Entity(self) -> Optional[Entity]: ...
    @Entity.setter
    def Entity(self, value: Entity) -> None: ...

class TransformComponent(Component):
    def __init__(self) -> None: ...
    @property
    def Position(self) -> vec3: ...
    @Position.setter
    def Position(self, value: vec3) -> None: ...
    @property
    def Rotation(self) -> vec3: ...
    @Rotation.setter
    def Rotation(self, value: vec3) -> None: ...
    @property
    def Scale(self) -> vec3: ...
    @Scale.setter
    def Scale(self, value: vec3) -> None: ...
    @property
    def LocalPosition(self) -> vec3: ...
    @LocalPosition.setter
    def LocalPosition(self, value: vec3) -> None: ...
    @property
    def LocalRotation(self) -> vec3: ...
    @LocalRotation.setter
    def LocalRotation(self, value: vec3) -> None: ...
    @property
    def LocalScale(self) -> vec3: ...
    @LocalScale.setter
    def LocalScale(self, value: vec3) -> None: ...
    @property
    def Forward(self) -> vec3: ...
    @property
    def Right(self) -> vec3: ...
    @property
    def Up(self) -> vec3: ...
    @property
    def Transform(self) -> ScriptTransform: ...
    @Transform.setter
    def Transform(self, value: ScriptTransform) -> None: ...

class MeshRendererComponent(Component):
    def __init__(self) -> None: ...
    @property
    def Mesh(self) -> Optional[Mesh]: ...
    @Mesh.setter
    def Mesh(self, value: Optional[Mesh]) -> None: ...
    @property
    def Material(self) -> Optional[Material]: ...
    @Material.setter
    def Material(self, value: Optional[Material]) -> None: ...
    @property
    def Materials(self) -> List[Optional[Material]]: ...
    @Materials.setter
    def Materials(self, value: List[Optional[Material]]) -> None: ...
    @property
    def MaterialCount(self) -> int: ...
    def GetMaterial(self, index: int) -> Optional[Material]: ...
    def SetMaterial(self, index: int, material: Optional[Material]) -> None: ...

class Behaviour(Component):
    def __init__(self) -> None: ...
    @property
    def ID(self) -> int: ...
    @ID.setter
    def ID(self, value: int) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> None: ...
    @property
    def Transform(self) -> TransformComponent: ...
    def GetComponent(self, cls: Type[T]) -> Optional[T]: ...
    def HasComponent(self, cls: type) -> bool: ...
    def CreateComponent(self, cls: Type[T]) -> Optional[T]: ...

# Native Data Structures
class ScriptTransform:
    """Transform 数据容器。"""
    Position: vec3
    Rotation: vec3
    Scale: vec3
    Up: vec3
    Right: vec3
    Forward: vec3
