# PrismEngine 原生模块类型存根

from typing import Optional, Type, TypeVar

T = TypeVar("T")

class vec3: ...

class vec4: ...

class Entity:
    """C++ PythonEntity 的 Python 绑定。"""

    def __init__(self, id: int = 0) -> None: ...

    @property
    def ID(self) -> int: ...
    @ID.setter
    def ID(self, value: int) -> None: ...

    @property
    def Transform(self) -> "TransformComponent": ...

    def GetComponent(self, cls: Type[T]) -> Optional[T]: ...
    def CreateComponent(self, cls: Type[T]) -> Optional[T]: ...
    def HasComponent(self, cls: type) -> bool: ...

    @staticmethod
    def FindEntityByTag(tag: str) -> Optional["Entity"]: ...

    @staticmethod
    def FindEntityByID(id: int) -> "Entity": ...


class Component:
    """C++ PythonComponent 的 Python 绑定。所有组件的基类。"""

    def __init__(self) -> None: ...

    @property
    def Entity(self) -> Optional[Entity]: ...
    @Entity.setter
    def Entity(self, value: Entity) -> None: ...


class TransformComponent(Component):
    """C++ PythonTransformComponent 的 Python 绑定。Rotation 单位为角度。"""

    def __init__(self) -> None: ...

    @property
    def Position(self) -> vec3: ...
    @Position.setter
    def Position(self, value: vec3) -> None: ...

    @property
    def Rotation(self) -> vec3: ...
    @Rotation.setter
    def Rotation(self, value: vec3) -> None: ...

    @property
    def Scale(self) -> vec3: ...
    @Scale.setter
    def Scale(self, value: vec3) -> None: ...

    @property
    def LocalPosition(self) -> vec3: ...
    @LocalPosition.setter
    def LocalPosition(self, value: vec3) -> None: ...

    @property
    def LocalRotation(self) -> vec3: ...
    @LocalRotation.setter
    def LocalRotation(self, value: vec3) -> None: ...

    @property
    def LocalScale(self) -> vec3: ...
    @LocalScale.setter
    def LocalScale(self, value: vec3) -> None: ...

    @property
    def Forward(self) -> vec3: ...
    @property
    def Right(self) -> vec3: ...
    @property
    def Up(self) -> vec3: ...

    @property
    def Transform(self) -> ScriptTransform: ...
    @Transform.setter
    def Transform(self, value: ScriptTransform) -> None: ...


class Behaviour(Component):
    """C++ PythonBehaviour 的 Python 绑定。用户脚本继承此类。"""

    def __init__(self) -> None: ...

    @property
    def ID(self) -> int: ...
    @ID.setter
    def ID(self, value: int) -> None: ...

    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> None: ...

    @property
    def Transform(self) -> TransformComponent: ...

    def GetComponent(self, cls: Type[T]) -> Optional[T]: ...
    def HasComponent(self, cls: type) -> bool: ...
    def CreateComponent(self, cls: Type[T]) -> Optional[T]: ...


class ScriptTransform:
    """Transform 数据容器。"""
    Position: vec3
    Rotation: vec3
    Scale: vec3
    Up: vec3
    Right: vec3
    Forward: vec3
