#ifndef PRISM_BINDINGS
#define PRISM_BINDINGS

#define PRISM_SET_FRAME     0
#define PRISM_SET_OBJECT    1
#define PRISM_SET_MATERIAL  2
#define PRISM_SET_TEXTURES  3

#if PRISM_BACKEND_OPENGL

#define PRISM_BINDING_FRAME    0
#define PRISM_BINDING_OBJECT   1
#define PRISM_BINDING_MATERIAL 2

#define PRISM_SHADOW_MAP0   3
#define PRISM_SHADOW_MAP1   4
#define PRISM_SHADOW_MAP2   5
#define PRISM_SHADOW_MAP3   6

#define PRISM_GEOMETRY_PASS_TEXTURE 7

#define PRISM_ENV_RADIANCE    8
#define PRISM_ENV_IRRADIANCE  9
#define PRISM_ENV_BRDF_LUT    10

#define PRISM_BLOOM_TEXTURE 11

#define PRISM_BINDING_TEXTURE 16

#elif PRISM_BACKEND_VULKAN

#define PRISM_BINDING_FRAME    0

#define PRISM_SHADOW_MAP0   1
#define PRISM_SHADOW_MAP1   2
#define PRISM_SHADOW_MAP2   3
#define PRISM_SHADOW_MAP3   4

#define PRISM_GEOMETRY_PASS_TEXTURE 5

#define PRISM_ENV_RADIANCE    6
#define PRISM_ENV_IRRADIANCE  7
#define PRISM_ENV_BRDF_LUT    8

#define PRISM_BLOOM_TEXTURE 9

#define PRISM_BINDING_OBJECT   0
#define PRISM_BINDING_MATERIAL 0

#endif

#endif
